### ISSUE TITLE
Missing `basicBuildWatch`

### ISSUE THREAD

**Issue by alinhle** [mattieb/turbotree#1]
Hey @mattieb,

thanks for working on this. I wanted to try it out, though there is no `basicBuildWatch` exported in this library, even though it's part of the docs.

Best regards,

Vinh

**Comment by mattieb** [comment]
Thanks for the heads up! That was an old name I had been using when I was developing. I decided halfway through to change it so we could support more descriptive prebuilt expressions that shipped with the library, but missed that documentation. Should be good now. 🙂

**Comment by ericanderson** [comment]
@mattieb The published version has a readme that still is wrong fyi
